Plugin Modernization
jenkinsci/startup-trigger-plugin pull request #8
Opened 2023-09-19 10:31 UTC by gounthar

I have followed most of the [Improve a Plugin Tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/).

### Testing done

`mvn clean install`

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Link to relevant pull requests, esp. upstream and downstream changes~~
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-09-20 13:50 UTC, MarkEWaite commented
I launched the ci.jenkins.io job with the new Jenkinsfile.

2023-09-20 13:54 UTC, gounthar commented
Thanks a lot, Mark, we'll see if this build is better than the previous one. 👍

2023-09-20 14:47 UTC, gounthar commented
All the checks passed. 🚀 
I think the previous build error was due to an incompatibility of some sort between our current BOM dependencies and JDK8 (super wild guess, I have no data to prove it).

2023-09-20 17:56 UTC, MarkEWaite requested changes
Minimum Jenkins version should match with the bom version

2023-09-20 17:56 UTC, MarkEWaite commented on pom.xml
> +        <jenkins.version>2.401.3</jenkins.version>
I think that the `jenkins.version` and the `bom` version should match.
```suggestion
        <jenkins.version>2.387.3</jenkins.version>

```

2023-09-20 18:02 UTC, gounthar commented
Thank you, Mark.
It appears that the issue arose after initially following the tutorial and subsequently entrusting Dependabot with my fork without a thorough review.

In brief, I made an error, and I am committed to rectifying it promptly.

2023-09-20 18:39 UTC, MarkEWaite commented
> entrusting Dependabot with my fork without a thorough review

That is an interesting challenge.  I am surprised that dependabot offered an update of the `jenkins.version` value.  I've never seen that.

2023-09-20 20:27 UTC, gounthar commented
Yes, that doesn't make much sense to me either...
I will check the list of commits and PRs on my fork and see where I failed.
Spoiler alert: I guess in the end I will find I'm the only one who's guilty, and the bot is innocent.

2023-09-20 20:50 UTC, MarkEWaite commented
No problem.  https://github.com/jenkinsci/startup-trigger-plugin/pull/8/commits/fec66f9f2615801646814550168863b5be0bd9af shows that when updating to make Jenkins 2.401.3 the minimum version, the bom line remained at `bom-2.387.x`.  No problem if the plugin chooses to require 2.401.3 or 2.387.3 as its minimum Jenkins version, but I think that it is healthy to keep the bom version matched with the Jenkins minimum version.

2023-09-21 07:23 UTC, gounthar commented
Thank you, Mark.

Now, I understand. It's because I followed the tutorial "[Update minimum required Jenkins version](https://www.jenkins.io/doc/developer/tutorial-improve/update-base-jenkins-version/#update-minimum-required-jenkins-version)" without thinking. The tutorial instructs you to update the version like this:

```xml
   <properties>
     <jenkins.version>2.401.3</jenkins.version>
   </properties>
```

and then to update the bill of materials accordingly... Using a diff such as:

 ```xml
 <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
-        <artifactId>bom-2.319.x</artifactId>
+        <artifactId>bom-2.387.x</artifactId>
-        <version>1466.v85a_616ea_b_87c</version>
+        <version>2179.v0884e842b_859</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

So, I noticed the version mentioned was 2.387, and I might have thought to myself, "I'm good; I have the same thing as the example is showing." However, I should have considered consistency and used the same version base. 😊

Is this part of the documentation something we should aim to keep updated using updatecli, or is it sufficient as it stands now? I mean, most Jenkins plugin developers will likely connect the dots automatically, which I, unfortunately, didn't manage to do. 🤷

2023-09-22 13:49 UTC, merged